services:
  - type: web
    name: uravu-backend
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
